export const TOOL_ERROR_CODES = [
  "WEBMCP_UNAVAILABLE",
  "SOURCE_DISCONNECTED",
  "TRACE_EMPTY",
  "TOOL_CANCELLED",
  "INVALID_CONTRACT",
  "UNKNOWN_PROVENANCE",
  "STALE_TRACE",
  "CONTRACT_NOT_FOUND",
  "CONTRACT_NOT_APPROVED",
  "TARGET_DISCONNECTED",
  "CAPABILITY_VERSION_INVALID",
  "PREVIEW_NOT_FOUND",
  "STALE_PREVIEW",
  "UNRESOLVED_DECISIONS",
  "TARGET_REJECTED_DRAFT",
  "DRAFT_NOT_PREPARED",
  "INVALID_TOOL_RESPONSE",
  "INVALID_SESSION",
] as const;

export type ToolErrorCode = (typeof TOOL_ERROR_CODES)[number];
